name: WOLS CA Uploader
version: "0.1.12"
slug: wols_ca_uploader
description: WOLS CA Uploader for Home Assistant
arch:
  - amd64
  - aarch64
startup: services
boot: auto
init: false
ingress: true
ingress_port: 8099
panel_icon: mdi:upload-network
ports:
  8099/tcp: null
ports_description:
  8099/tcp: Web UI
image: "ghcr.io/wolsca/wols-ca-uploader-alpine:{version}"
